# Generated by Django 3.1.6 on 2021-02-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('street_address', models.CharField(max_length=500)),
                ('contact_num', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=600)),
            ],
        ),
    ]
