# Generated by Django 3.1.6 on 2021-02-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testomonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicesinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('logo', models.CharField(max_length=400)),
            ],
        ),
    ]
